config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users


  get "/", to: "pages#home", as: "root"

  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/:listing_id/email_donator", to: "pages#show", as: "email_donator"
  get "/help", to: "pages#help", as: "help"
  get "/about", to: "pages#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing" 
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "/machines", to: "machines#index", as: "machines"
  post "/machines", to: "machines#create"
  get "/machines/new", to: "machines#new", as: "new_machine"
  get "/machines/:id", to: "machines#show", as: "machine" 
  put "/machines/:id", to: "machines#update"
  patch "/machines/:id", to: "machines#update"
  delete "/machines/:id", to: "machines#destroy"
  get "/machines/:id/edit", to: "machines#edit", as: "edit_machine"

  get "/years", to: "years#index", as: "years"
  post "/years", to: "years#create"
  get "/years/new", to: "years#new", as: "new_year"
  get "/years/:id", to: "years#show", as: "year" 
  put "/years/:id", to: "years#update"
  patch "/years/:id", to: "years#update"
  delete "/years/:id", to: "years#destroy"
  get "/years/:id/edit", to: "years#edit", as: "edit_year"

  get "/systems", to: "systems#index", as: "systems"
  post "/systems", to: "systems#create"
  get "/systems/new", to: "systems#new", as: "new_system"
  get "/systems/:id", to: "systems#show", as: "system" 
  put "/systems/:id", to: "systems#update"
  patch "/systems/:id", to: "systems#update"
  delete "/systems/:id", to: "systems#destroy"
  get "/systems/:id/edit", to: "systems#edit", as: "edit_system"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition" 
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/donations", to: "donations#index", as: "donations"
  post "/donations", to: "donations#create"
  get "/donations/new", to: "donations#new", as: "new_donation"
  get "/donations/:id", to: "donations#show", as: "donation" 
  put "/donations/:id", to: "donations#update"
  patch "/donations/:id", to: "donations#update"
  delete "/donations/:id", to: "donations#destroy"
  get "/donations/:id/edit", to: "donations#edit", as: "edit_donation"
  

  get "/payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? 'rails/active_storage' } #can type any garbage and still go to page is not found. that * 
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :system
  belongs_to :year
  belongs_to :condition
  belongs_to :machine

  enum is_donated: { pending: 0, published: 1 }

  has_one_attached :picture

  max_paginates_per 6

  validates :description, presence: true,
            length: { minimum: 10 }

  validates :title, presence: true,
            length: { minimum: 5 }          

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

### Users can see the index of the listings, but need to sign up or login if they wish to see the 'show' page.
### Admin has CRUD access using cancancan gem. 

  load_and_authorize_resource
  skip_authorize_resource :only => :show 
  before_action :authenticate_user!, only: [:show]
  before_action :set_listing, only: [:show] 
  #before_action :set_user_listing, only: [ :edit, :update, :destroy ]
  
  
  def index 
  ### This is using the ransack and kaminari gems so users can search the listings and the listings are arranged appropriately on each page.
    @q = Listing.ransack(params[:q])
    @listings = @q.result.includes(:machine, :system, :condition, :year)
    @listings = @listings.order('created_at DESC').page(params[:page]).per(12)
  end

  
#This creates the object instance @listing
  def new
    @listing = Listing.new
  end

  def show
    id = params[:id]
    @listing = Listing.find(id)

    if @listing == nil
      redirect_to root_path
    end 
  end

# This will create a new listing and then save it to the database provided it satisfies the parameters 
  def create
    listing_params = params.require(:listing).permit(:title, :description, :system_id, :year_id, :condition_id, :location, :machine_id, :data_wiped, :is_donated, :picture) 
    
    @listing = current_user.listings.new( listing_params )
  
    if @listing.save && @listing.data_wiped == true
      @listing.is_donated = 'published'
      @listing.save
    else 
      @listing.is_donated = 'pending'
      @listing.save
    end 

    if @listing.save 
    
    redirect_to @listing 
    else 
      render :new 
    end 
     
  end

# This updates the listing and then saves it to the database
  def update
    if @listing.update( listing_params ) && @listing.data_wiped == true
      @listing.is_donated = 'published'
      @listing.save    
    else @listing.update( listing_params ) && @listing.data_wiped == false || @listing.update( listing_params ) && @listing.data_wiped == nil
      @listing.is_donated = 'pending'
      @listing.save   
    end 
    
    if @listing.update( listing_params )
      redirect_to @listing
    else 
      render :edit
    end 
  end

#This provides the method for deleting from the database
  def destroy
    @listing.destroy
    redirect_to root_path
  end


  private

  
  def set_listing 
    id = params[:id]
    @listing = Listing.find(id)
  end 

  def listing_params
    params.require(:listing).permit(:title, :description, :system_id, :year_id, :condition_id, :location, :machine_id, :data_wiped, :is_donated, :picture)
  end 

  def set_user_listing
    id = params[:id]
    @listing = current_user.listings.find_by_id( id )

    if @listing == nil
      redirect_to listings_path
    
    end 
  end 

end 

app/views/listings/_form.html.erb
<%= form_with model: listing, local:true do |form| %>

<!-- Error messages will appear if the field is not filled in by the admin user -->

<div class="listingwholeform">

<div class="listingerrors">
<% if listing.errors.any? %>

  <div id="error_explanation">
    <p class="perrors"><%= pluralize(@listing.errors.count, "error") %> prohibited this form from being saved:</p>
 
    <ul>
    <% @listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

<div>
  <%= form.label :title, :class => "label-field"%>
  <%= form.text_field :title, :required => true, :autofocus => true, :placeholder => "What are you selling?", :class => "placeholder"%>
</div>

<div>
  <%= form.label :description, :class => "label-field"%>
  <%= form.text_area :description, :placeholder => "Type something here", :class => "placeholder" %>
</div>

<div>
<%= form.label 'Operating System', :class => "label-field" %>
<%= form.select :system_id,
options_for_select( System.all.collect { |u| [u.name, u.id] },
:selected => listing.system_id ) %>
</div>

<div>
<%= form.label :year_id, :class => "label-field" %>
<%= form.select :year_id,
options_for_select( Year.all.collect { |u| [u.name, u.id] },
:selected => listing.year_id ) %>
</div>

<div>
  <%= form.label :condition_id, :class => "label-field" %>
  <%= form.select :condition_id,
  options_for_select( Condition.all.collect { |u| [u.condition, u.id] }, :selected => listing.condition_id ) %>
</div>

<div>
<%= form.label :location, :class => "label-field" %>
<%= form.select :location, ["Adelaide, SA", "Brisbane, QLD", "Canberra, ACT", "Hobart, Tas", "Melbourne, Vic", "Perth, WA", "Sydney, NSW", "Darwin, NT" ]%>
</div>

<div>
  <%= form.label 'Type', :class => "label-field" %>
  <%= form.select :machine_id,
  options_for_select( Machine.all.collect { |u| [u.name, u.id] },
  :selected => listing.machine_id ) %>
</div>

<div>
<%= form.label 'Is it restored to factory settings?', :class => "label-field" %>
<br>
<%= form.label :data_wiped, "Yes", :value => true, :class =>"radio-text" %>
<%= form.radio_button :data_wiped, true %>

<%= form.label :data_wiped, "No", :value => false, :class => "radio-text" %>
<%= form.radio_button :data_wiped, false %>
</div>

<div>
<%= form.label 'Please attach a picture', :class => "label-field" %>
<br>
<div class="photobut">
  <div class="but">
<%= form.file_field :picture, accept: 'image/png,image/gif,image/jpg,image/jpeg' %>
  </div>
</div>
</div>

<br>

<div>
  <%= form.submit 'Submit', :class => "blue-button" %>
</div>

<% end %>

</div>

app/views/listings/edit.html.erb
<%= render "/pages/navbar" %>
<body>
  </main>
    <div class="list-form">
      <div class="list-form-all">  
        <div class="list-form-heading">
          <h1 class="h1-listing">Edit Tech Listing</h1>
            
        </div>  
        <br>
            <%= render 'form', listing: @listing%>
        
      </div>
    </div>
     <%= render '/pages/footer' %>
  </main>
</body>

app/views/listings/index.html.erb
<%= render "pages/navbar" %>

<div>
<%= search_form_for @q do |f| %>
  <%= f.label :'Search titles and location' %>
  <%= f.search_field :title_or_description_or_location_cont  %>
  <%= f.submit %>
<% end %>
</div>

<!-- Kaminari gem that enables a specific number of listings to be listed per page -->
  <%= paginate @listings %>

<div class="listing-hero">
<h1>Donated Tech</h1>
</div>


<div class="index-card">
  <% @listings.each do |listing|%>
    <% if listing.data_wiped == true %>

    <div class="index-card-content">
      <div class="img-container-index">
          <span><%= image_tag listing.picture, class: 'thumbnail-index' if listing.picture.attached? %></span>
      </div>
      <span><strong><%= listing.title %></strong></span>
      <span>Operating system: <%= listing.system.name %></span>
      <span>Year: <%= listing.year.name %></span>
      <span>Location: <%= listing.location %></span>
      <span>
        <%= link_to "View", listing_path( listing ) %>
      </span>
    </div>   
      <% end %>
      
  <% end %>
  </div>



<%= render 'pages/footer' %>

app/views/listings/new.html.erb
<%= render "/pages/navbar" %>
<body>
  </main>
    <div class="list-form">
      <div class="list-form-all">  
        <div class="list-form-heading">
          <h1 class="h1-listing">New Tech Donation</h1>
            
        </div>  
        <br>
            <%= render 'form', listing: @listing%>
        
      </div>
    </div>
     <%= render '/pages/footer' %>
  </main>
</body>

app/views/listings/show.html.erb
<%= render "/pages/navbar" %>
<section class="show_single_list">
  <div class="show-container">
    <div class="show-all">
        <div class="show-content">
       
<h1 class="h1-show">Tech listing</h1>
  
<p class="show-user">
<% if @listing.user_id == current_user.id %>
<% if @listing.data_wiped == true %>
<%= "Thank you so much! This listing has been published." %>
<% else %>
<%= "Thank you so much! This listing is pending. Someone will be in touch with you about restoring your tech to factory settings." %>
<% end %>
<% end %>
</p>
<p class="image-show"> 
<%= image_tag @listing.picture, class: 'thumbnails' if @listing.picture.attached?  %>
</p>
<p>
<strong>Title:</strong>
<%= @listing.title %>
</p>
<p class="show-description">
<strong>Description</strong>
<%= @listing.description %>
</p>
<p>
<strong>Computer System</strong>
<% if @listing.system != nil %>
<%= @listing.system.name %>
<% end %>
</p>
<p>
<strong>Year</strong>
<%= @listing.year.name %>
</p>
<p>
<strong>Condition</strong>
<%= @listing.condition.condition %>
</p>
<p>
<strong>Location</strong>
<%= @listing.location %>
</p>
<p>
<strong>Machine</strong>
<%= @listing.machine.name %>
</p>

<p>
<strong>Data wiped</strong>
<% if @listing.data_wiped == true %>
        <%= "Yes" %>
        <% else  %>
        <%= "No" %>
        <% end %>
</p>

<!-- User will only see this request button if they are not the one to list the item -->
<% if current_user.id != @listing.user_id %>
<div class="blue-button-request">

<%= link_to "Request item", email_donator_path(@listing), class:"request-link" %>
<% end %>

<% if current_user.id == @listing.user_id %>
<%= link_to "Edit", edit_listing_path(@listing) %>
<%= link_to 'Destroy', listing_path(@listing),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %>
        </div>
<% end %>
       
    </div>
  </div>


</section>
<%= render '/pages/footer' %>