config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users


  get "/", to: "pages#home", as: "root"

  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/:listing_id/email_donator", to: "pages#show", as: "email_donator"
  get "/help", to: "pages#help", as: "help"
  get "/about", to: "pages#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing" 
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "/machines", to: "machines#index", as: "machines"
  post "/machines", to: "machines#create"
  get "/machines/new", to: "machines#new", as: "new_machine"
  get "/machines/:id", to: "machines#show", as: "machine" 
  put "/machines/:id", to: "machines#update"
  patch "/machines/:id", to: "machines#update"
  delete "/machines/:id", to: "machines#destroy"
  get "/machines/:id/edit", to: "machines#edit", as: "edit_machine"

  get "/years", to: "years#index", as: "years"
  post "/years", to: "years#create"
  get "/years/new", to: "years#new", as: "new_year"
  get "/years/:id", to: "years#show", as: "year" 
  put "/years/:id", to: "years#update"
  patch "/years/:id", to: "years#update"
  delete "/years/:id", to: "years#destroy"
  get "/years/:id/edit", to: "years#edit", as: "edit_year"

  get "/systems", to: "systems#index", as: "systems"
  post "/systems", to: "systems#create"
  get "/systems/new", to: "systems#new", as: "new_system"
  get "/systems/:id", to: "systems#show", as: "system" 
  put "/systems/:id", to: "systems#update"
  patch "/systems/:id", to: "systems#update"
  delete "/systems/:id", to: "systems#destroy"
  get "/systems/:id/edit", to: "systems#edit", as: "edit_system"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition" 
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/donations", to: "donations#index", as: "donations"
  post "/donations", to: "donations#create"
  get "/donations/new", to: "donations#new", as: "new_donation"
  get "/donations/:id", to: "donations#show", as: "donation" 
  put "/donations/:id", to: "donations#update"
  patch "/donations/:id", to: "donations#update"
  delete "/donations/:id", to: "donations#destroy"
  get "/donations/:id/edit", to: "donations#edit", as: "edit_donation"
  

  get "/payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? 'rails/active_storage' } #can type any garbage and still go to page is not found. that * 
end

app/views/pages/_all_listings.html.erb
<%= render "/pages/navbar" %>

<div class="all-listings-heading">
<h1>Donated Tech - Admin dash</h1>
<p class="p-usertable">You are an admin and currently logged in as <strong><%= current_user.email %></strong></p>
</div>



<div class="listing-all">
<table id="listing">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Operating System</th>
    <th>Year</th>
    <th>Condition</th>
    <th>Machine type</th>
    <th>Location</th>
    <th>Restored factory settings?</th>
    <th>Tech status</th>
    <th>User</th>
    <th>Image</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
<% @listings = Listing.all %>
<% @listings.each do |listing|%>
  <tr class="listing-row">
    <td><%= listing.title %></td>
    <td><%= listing.description %></td>
    <td>
      <% if listing.system != nil %>
      <%= listing.system.name %>
      <% end %>
    </td>
    <td><%= listing.year.name %></td>
    <td><%= listing.condition.condition %></td>
    <td><%= listing.machine.name %></td>
    <td><%= listing.location %></td>
    <td>
      <% if listing.data_wiped == true %>
      <%= "Yes" %>
      <% else  %>
      <%= "No" %>
      <% end %>
    </td>
  
    <td><%=listing.is_donated%></td>
    <td><%= listing.user.email %></td>
    <td><%= image_tag listing.picture, class: 'thumbnails' if listing.picture.attached? %></td>
    <td><%= link_to "View", listing_path( listing ) %></td>
      <%if current_user%>
        <%if current_user.admin? || current_user.id == listing.user_id %>
    <td><%= link_to 'Edit', edit_listing_path(listing), class:"listing-link" %></td>
    <td><%= link_to 'Destroy', listing_path(listing),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %></td>
        <% else  %> 
    </tr>   
        <%end%>
      <%end%>
  
</tbody>
<%end%>
</table>

</div>
<br>

app/views/pages/_footer.html.erb
<footer>
    <div class="footer-links">
        <a href="http://github.com/themishmash" target="_blank">
            <i class="fab fa-github footer-link"> </i>
        </a>
        <a href="http://www.linkedin.com/in/wong-mich" target="_blank">
        <i class="fab fa-linkedin footer-link"></i>
        </a>
    </div>
    <div class="footer-tagline">
      <p>Made with <i class="fas fa-heart heart-logo"></i>.</p>
    </div>
</footer>

app/views/pages/_navbar.html.erb
<nav class="nav">
  <ul>
    <div class="navbar-links">
    <li><%= link_to "HOME", root_path, class: "navbar-link" %></li>
    <li><%= link_to "ABOUT", about_path, class: "navbar-link" %></li>
    <li><%= link_to "TECH LISTINGS", listings_path, class: "navbar-link" %></li>
    <li><%= link_to "DONATE", new_donation_path, class: "navbar-link" %></li>
    <li>
    <li><%= link_to "CONTACT", root_path, class: "navbar-link" %></li>
    
 <% if user_signed_in? %>
  <div class="dropdown">
    <li class="dropbtn">
    <%= link_to "MY PROFILE", user_path, class: "navbar-link" %>
    </li>
    <div class="dropdown-content">
      <%= link_to "Add new tech", new_listing_path %>
      <%= link_to "My listings", user_path %>
    </div>
  </div>
  <% end %>
 
    <li>
    <% if user_signed_in? %>
    <%= link_to "LOGOUT", destroy_user_session_path, class: "navbar-link", method: :delete %>
    <% else %>
    <%= link_to "LOGIN", new_user_session_path, class: "navbar-link" %>
    <% end %>
    </li>

    <%if current_user %>
      <div class="dropdown">
        <li class="dropbtn">
          <% if current_user.admin? %>
          <%= link_to "ADMIN", admin_path, class: "navbar-link" %>
        </li>
        <div class="dropdown-content">
        <%= link_to "All listings", admin_path %>
        <%= link_to 'View Machines', machines_path %>
        <%= link_to 'View Years', years_path%>
        <%= link_to 'View Systems', systems_path%>
        <%= link_to 'View Conditions', conditions_path %>
        <%= link_to 'View Donations', donations_path %>
        </div>
        </div>
          <% end %>
    <% end %>
    </div>
    <div class="navbar-logo">
      <img src="/assets/white-greyback.png" alt="tech-exchange-logo" class="img-techexchange">
    
  </div>
  </ul>
</nav>

app/views/pages/about.html.erb
<%= render "navbar" %>

<div class="about-container">
  <div class="about-all">

    <div class="about-headings">
      <div class="h1-about">
        <h1 class="h1aboutfont"> About Us </h1>
      </div>
      <div class="h3-about">
        <h3 class="h3-aboutfont">Thanks for dropping by!</h3>
      </div>
    </div>

    <div class="text-about">
<p class="p-about">The Tech Exchange is a not-for-profit organisation run mostly by volunteers.</p>
<br>
<p>We connect people who have unwanted tech to those who do not have the financial means to access better technology.</p>
<br>
<p>If you want to donate your tech, all you have to do is sign up, list your tech on our website and then you wait to be contacted.</p>
<br>
<p>If you want to receive donated tech, all you have to do is sign up and contact the person who has posted the listing.</p> 
<br>
<p>If you don't have any tech but would like to help, you can contact us about your skills or donate money. Any money is greatly appreciated as it is used to repair computers, wipe data and send computers all around Australia, including remote locations!</p>
<br>
<p>Be the change you wish to see in the world.</p>
<br>
<p>Sign up to the Tech Exchange today!</p>
    </div>
  </div>
</div>

<%= render 'footer' %>

app/views/pages/admin.html.erb
<%=  render 'all_listings' %> 

<%= render 'footer' %>

app/views/pages/home.html.erb
<div class="home-background">
<%= render 'navbar' %>

<body>
<main>

<div class="hero-text">
  <div class="hero-stuff">
<h1 class="h1-pages">Breathe life into old tech.</h1>
<h1 class="h2-pages">Donate unwanted computers and laptops to the Tech Exchange.</h1>
 
 <div class="arrow">
 <div>
  <i class="fas fa-angle-double-down double-arrow"></i>
  </div>
  </div>
  </div>
</div>

<div class="recent-listing-hero">
<div>
<h3>Recent listings</h3>
</div>
</div>

<div class="content2">
<div class="content">
<% @listings = Listing.all.select { |l| l.data_wiped == true } %>
  <% @listings.last(8).each do |listing|%>
    <div class="card-content">
      <span><strong><%= listing.title %></strong></span>
      <span><%= image_tag listing.picture, class: 'background-image' if listing.picture.attached? %></span>
      <span>Operating System: <%= listing.system.name %></span>
      <span>Year: <%= listing.year.name %></span>
      <span>Condition: <%= listing.condition.condition %></span>
      <span>Location: <%= listing.location %></span>
      <span><%= link_to "View", listing_path( listing ) %></span>
    </div>
  <% end %>
</div>
</div>
<%= render 'footer' %>
</main>
</body>
</div>

app/views/pages/not_found.html.erb
<h1>This page is not found</h1>

app/views/pages/show.html.erb
<%= render 'pages/navbar' %>
<div class="donate-container">
  <div class="donate-all">
    <div class="donate-all2">

<h1>Donator Details</h1>

<p>Please contact the user at the email below for more information or to request this item</p>
<br>
<br>
<strong><%= @listing.user.email %></strong>

    </div>
  </div>
</div>

<%= render 'footer' %>

app/views/pages/user.html.erb
<%= render "/pages/navbar" %>

<div class="user-listing-heading">
<h1>My Donated Tech</h1>
<p class="p-usertable">You are currently logged in as <strong><%= current_user.email %></strong></p>
</div>

<div class="listing-table">
  <div class="listing-table2">
<table id="listing">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Operating System</th>
      <th>Year</th>
      <th>Condition</th>
      <th>Machine type</th>
      <th>Location</th>
      <th>Restored factory settings</th>
      <th>Tech status</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @listings = Listing.all %>
<% @listings.each do |listing|%>
<% if current_user %>
<% if listing.user_id == current_user.id %>
  <tr class="listing-row">
    <td><%= listing.title %></td>
    <td><%= listing.description %></td>

    <td>
      <% if listing.system != nil %>
      <%= listing.system.name %>
      <% end %>
    </td>
    <td><%= listing.year.name %></td>
    <td><%= listing.condition.condition %></td>
    <td><%= listing.machine.name %></td>
    <td><%= listing.location %></td>
    <td>
        <% if listing.data_wiped == true %>
        <%= "Yes" %>
        <% else  %>
        <%= "No" %>
        <% end %>
    <td><%=listing.is_donated%></td>
    </td>
    <td><%= image_tag listing.picture, class: 'thumbnails' if listing.picture.attached? %></td>
    <td><%= link_to "View", listing_path( listing ) %></td>
    
    <% if current_user %>
      <% if current_user.admin? || current_user.id == listing.user_id %>
    <td><%= link_to 'Edit', edit_listing_path(listing), class:"listing-link" %></td>
    <td><%= link_to 'Destroy', listing_path(listing),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %></td>
         <% else  %> 
         </tr>   
    <% end %>
    <% end %>
<% end %>
<% end %>

</tbody>
<% end %>
</table>
  </div>
</div>

<%= render 'footer' %>