config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users


  get "/", to: "pages#home", as: "root"

  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/:listing_id/email_donator", to: "pages#show", as: "email_donator"
  get "/help", to: "pages#help", as: "help"
  get "/about", to: "pages#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing" 
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "/machines", to: "machines#index", as: "machines"
  post "/machines", to: "machines#create"
  get "/machines/new", to: "machines#new", as: "new_machine"
  get "/machines/:id", to: "machines#show", as: "machine" 
  put "/machines/:id", to: "machines#update"
  patch "/machines/:id", to: "machines#update"
  delete "/machines/:id", to: "machines#destroy"
  get "/machines/:id/edit", to: "machines#edit", as: "edit_machine"

  get "/years", to: "years#index", as: "years"
  post "/years", to: "years#create"
  get "/years/new", to: "years#new", as: "new_year"
  get "/years/:id", to: "years#show", as: "year" 
  put "/years/:id", to: "years#update"
  patch "/years/:id", to: "years#update"
  delete "/years/:id", to: "years#destroy"
  get "/years/:id/edit", to: "years#edit", as: "edit_year"

  get "/systems", to: "systems#index", as: "systems"
  post "/systems", to: "systems#create"
  get "/systems/new", to: "systems#new", as: "new_system"
  get "/systems/:id", to: "systems#show", as: "system" 
  put "/systems/:id", to: "systems#update"
  patch "/systems/:id", to: "systems#update"
  delete "/systems/:id", to: "systems#destroy"
  get "/systems/:id/edit", to: "systems#edit", as: "edit_system"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition" 
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/donations", to: "donations#index", as: "donations"
  post "/donations", to: "donations#create"
  get "/donations/new", to: "donations#new", as: "new_donation"
  get "/donations/:id", to: "donations#show", as: "donation" 
  put "/donations/:id", to: "donations#update"
  patch "/donations/:id", to: "donations#update"
  delete "/donations/:id", to: "donations#destroy"
  get "/donations/:id/edit", to: "donations#edit", as: "edit_donation"
  

  get "/payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? 'rails/active_storage' } #can type any garbage and still go to page is not found. that * 
end

app/models/donation.rb
class Donation < ApplicationRecord

  validates :amount, numericality: true
  validates :name, presence: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

#### Visitors to this site can make a donation without signing up or logging in, which is why they can read and create.
### Admin has crud access to this site using cancancan gem

load_and_authorize_resource
skip_authorize_resource :only => [:show, :new, :create]


  def home
  end 

  def index
    @donations = Donation.all
  end 

#This creates the object instance @donation
  def new
    @donation = Donation.new

  end 


#### This is connecting to a Stripe session using stripe's API 

  def show #line items for stripe. Line items is an array. 
     @donation = Donation.find(params[:id])

    session = Stripe::Checkout::Session.create(
      payment_method_types: [ 'card'],
      line_items: [{
        name: @donation.name,
        description: @donation.amount,
        amount: @donation.amount * 100, 
        currency: 'aud', 
        quantity: 1
      }],

      payment_intent_data: {
        metadata: {
          # user_id: current_user.id, 
          donation_id: @donation.id
        }
      },

      #This is where we want it to go when it succeeds. Root URL supplements your website and action want to take when success. 
      success_url: "#{root_url}payments/success?donationID=#{@donation.id}", 
      cancel_url: "#{root_url}donations"

)
  @session_id = session.id

  end

# This will create a new donation provided it satisifes the parameters and then save to the database
  def create
    donation_params
    @donation = Donation.new(donation_params)
    if @donation.save
      redirect_to @donation
    else 
      render :new
    end 
  end 

# Donation can be updated and then saved to the database
  def update
    if @donation.update (donation_params)
      redirect_to @donation
    end 
  end 

# This provides the method for deleting from the database
  def destroy
    @donation.destroy
    redirect_to root_path
  end 

private
  def set_donation
    id = params[:id]
    @donation = Donation.find(id)
  end 

  def donation_params
    params.require(:donation).permit(:name, :amount)
  end

end 

app/views/donations/_form.html.erb
<%= form_with model: @donation, local:true do |form| %>
<!-- Error messages will appear if the field is not filled in by the admin user -->

<div class="formanderrors">
  <div class="formanderrors2">
    <div class="error-explain">
      <% if @donation.errors.any? %>
        <div id="error_explanation">
          <p class="perrors"><%= pluralize(@donation.errors.count, "error") %> prohibited this form from being saved:</p>
          <tr>
          <% @donation.errors.full_messages.each do |msg| %>
          <td><%= msg %></td>
          <% end %>
          </tr>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.label :name, :class => "label-field" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :amount, :class => "label-field" %>
      <%= form.number_field :amount, min: 0, :placeholder => "Use arrows for donation", :class => "placeholder" %>
    </div>
    <div class="submit">
      <%= form.submit 'Confirm', :class => "don-blue-button" %>
    </div>

<% end %>
  </div>
</div>

app/views/donations/edit.html.erb
<%= render 'pages/navbar' %>

<div class="edit-mod-form">
  <div class="edit-don-form-all">

<h1 class="h1-mod-form"> Edit Donation</h1>

<%= render 'form', donation: @donation%>

</div>
</div>

<%= render 'pages/footer' %>

app/views/donations/index.html.erb
<!-- Only admin user can access this page -->

<%= render "/pages/navbar" %>

<% if current_user %>
<% if current_user.admin? %>
<div class="listing-hero">
<h1>Donation Quick stats</h1>
</div>
<div class="machine-table">
  <div class="machine-table2">
<table id="listing">
  <thead>
    <tr>
      <th>Number of donators</th>
      <th>Sum of donations</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td><%= Donation.count(:name) %></td>
    <td><%= Donation.sum(:amount) %></td>
  </tr>
</tbody>
</table>
</div>
</div>


<div class="listing-hero">
<h1>Donations Listing</h1>
</div>
<div class="machine-table">
  <div class="machine-table2">
<table id="listing">
<thead>
  <tr>
    <th>Donator's name</th>
    <th>Amount</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
<% @donations.each do |donation|%>
  <tr class="listing-row">
    <td><%= donation.name %></td>
    <td><%= donation.amount %></td>
    <td><%= donation.created_at %></td>
    <td><%= donation.updated_at %></td>

  <td><%= link_to 'Edit', edit_donation_path(donation), class:"listing-link" %></td>
    <td><%= link_to 'Destroy', donation_path(donation),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %></td>
<% end %>
  </tr>
</tbody>
</table>

<br>
    

<%= link_to 'Add new donation', new_donation_path, class:"blue-button-donation" %>
<% end %>
<% end %>

</div>
</div>

<%= render 'pages/footer' %>

app/views/donations/new.html.erb
<%= render 'pages/navbar' %>
<body>
  </main>
  <div class ="form">
   <div class="don-form-all">
    <div class="form-heading-donation">
      <h1 class="h1donation"> Donate to the Tech Exchange today! </h1>
      <br>
      <br>

      <p> If you don't have any unused or unwanted tech lying around and would still like to help, we would greatly appreciate any donations you can spare. Donations are put towards ensuring the tech is restored to factory settings and for postage costs.</p>
    </div>

      <div class="donform">
    <%= render 'form' %>
      </div>

    </div>
  </div>


<%= render 'pages/footer' %>
</main>
</body>

app/views/donations/show.html.erb
<!-- This is the confirmation page to get to Stripe so user can enter in their name, payment details -->

<%= render "/pages/navbar" %>
<section class="show_single_list">

<div class="donate-container">
  <div class="donate-all-stripe">
    <div class="donate-all2">
    <h1 class="h1donate-stripe">Connect to Stripe</h1>
      <p> 
      Please click the link below to connect to stripe.
      <br>
      <%= "Name: #{@donation.name}" %>
      </p>
      <p> 
      <%= "Amount: $#{@donation.amount}"  %>
      </p>

      <div class="stripe-container">
        <div class="stripebutton">
      <button data-stripe="payment">
        Stripe payment <%= number_to_currency(@donation.amount) %>
      </button>
        

      <script src="https://js.stripe.com/v3/"></script>
      <script>
        document
          .querySelector("[data-stripe='payment']")
          .addEventListener("click", () => {
            const stripe = Stripe(
              "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
            );
            stripe.redirectToCheckout({
              sessionId: "<%= @session_id %>"
            });
          });
      </script>

      </div>
      </div>
    </div>
  </div>
</div>

</section>
<%= render '/pages/footer' %>