config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users


  get "/", to: "pages#home", as: "root"

  get "/admin", to: "pages#admin", as: "admin"
  get "/user", to: "pages#user", as: "user"

  get "/:listing_id/email_donator", to: "pages#show", as: "email_donator"
  get "/help", to: "pages#help", as: "help"
  get "/about", to: "pages#about", as: "about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing" 
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


  get "/machines", to: "machines#index", as: "machines"
  post "/machines", to: "machines#create"
  get "/machines/new", to: "machines#new", as: "new_machine"
  get "/machines/:id", to: "machines#show", as: "machine" 
  put "/machines/:id", to: "machines#update"
  patch "/machines/:id", to: "machines#update"
  delete "/machines/:id", to: "machines#destroy"
  get "/machines/:id/edit", to: "machines#edit", as: "edit_machine"

  get "/years", to: "years#index", as: "years"
  post "/years", to: "years#create"
  get "/years/new", to: "years#new", as: "new_year"
  get "/years/:id", to: "years#show", as: "year" 
  put "/years/:id", to: "years#update"
  patch "/years/:id", to: "years#update"
  delete "/years/:id", to: "years#destroy"
  get "/years/:id/edit", to: "years#edit", as: "edit_year"

  get "/systems", to: "systems#index", as: "systems"
  post "/systems", to: "systems#create"
  get "/systems/new", to: "systems#new", as: "new_system"
  get "/systems/:id", to: "systems#show", as: "system" 
  put "/systems/:id", to: "systems#update"
  patch "/systems/:id", to: "systems#update"
  delete "/systems/:id", to: "systems#destroy"
  get "/systems/:id/edit", to: "systems#edit", as: "edit_system"

  get "/conditions", to: "conditions#index", as: "conditions"
  post "/conditions", to: "conditions#create"
  get "/conditions/new", to: "conditions#new", as: "new_condition"
  get "/conditions/:id", to: "conditions#show", as: "condition" 
  put "/conditions/:id", to: "conditions#update"
  patch "/conditions/:id", to: "conditions#update"
  delete "/conditions/:id", to: "conditions#destroy"
  get "/conditions/:id/edit", to: "conditions#edit", as: "edit_condition"

  get "/donations", to: "donations#index", as: "donations"
  post "/donations", to: "donations#create"
  get "/donations/new", to: "donations#new", as: "new_donation"
  get "/donations/:id", to: "donations#show", as: "donation" 
  put "/donations/:id", to: "donations#update"
  patch "/donations/:id", to: "donations#update"
  delete "/donations/:id", to: "donations#destroy"
  get "/donations/:id/edit", to: "donations#edit", as: "edit_donation"
  

  get "/payments/success", to: "payments#success"
  post "payments/webhook", to: "payments#webhook"

  get "*path", to: "pages#not_found", constraints: lambda { |req| req.path.exclude? 'rails/active_storage' } #can type any garbage and still go to page is not found. that * 
end

app/models/machine.rb
class Machine < ApplicationRecord
  has_many :listings
  
  validates :name, presence: true

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  ### Admin has crud access to this site using cancancan gem
  ### This controller is used to create a new tech machine such as laptop, computer, tablet etc

  load_and_authorize_resource
  

  def index
    @machines = Machine.all
  end 

  #### creates an object instance of machine
  def new
    @machine = Machine.new
  end 


  def edit
  end 

  def show

    id = params[:id]
    @machine = Machine.find(id)

  end 

  ### This will create a new machine provided it satisfies the parameters and then save to the database
  def create
    machine_params

    @machine = Machine.new( machine_params )

    if @machine.save
      redirect_to @machine
    else 
      render :new
    end 

  end 

#Machine can be updated and then saved to the database
  def update
    if @machine.update( machine_params )
      redirect_to @machine
    end 
  end 

# This provides the method for deleting from the database
  def destroy
    @machine.destroy

    redirect_to root_path
  end 


private

  def set_machine
    id = params[:id]
    @machine = Machine.find(id)
  end 

  def machine_params
    params.require(:machine).permit(:name)
  end 


end 

app/views/machines/_form.html.erb
<%= form_with model: machine, local:true do |form| %>
<!-- Error messages will appear if the field is not filled in by the admin user -->
<div class="formanderrors">
  <div class="formanderrors2">
    <div class="error-explain">
<% if machine.errors.any? %>
  <div id="error_explanation">
    <p class="perrors"><%= pluralize(@machine.errors.count, "error") %> prohibited this form from being saved:</p>
 
    <ul>
    <% @machine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.submit 'Submit' %>
</div>

<% end %>

</div>
</div>

app/views/machines/edit.html.erb
<%= render 'pages/navbar' %>

<div class="edit-mod-form">
  <div class="edit-mod-form-all">
<h1 class="h1-mod-form"> Edit Machine</h1>

<%= render 'form', machine: @machine%>

</div>
</div>

<%= render 'pages/footer' %>

app/views/machines/index.html.erb
<%= render "/pages/navbar" %>

<div class="listing-hero">
<h1>Type of Machine</h1>
</div>

<div class="machine-table">
  <div class="machine-table2">
<table id="listing">
<thead>
  <tr>
    <th>Name of machine</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>

<% @machines.each do |machine|%>
  <tr class="listing-row">
    <td><%= machine.name %></td>
  <td><%= link_to 'Edit', edit_machine_path(machine), class:"listing-link" %></td>
    <td><%= link_to 'Destroy', machine_path(machine),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %></td>

<% end %>

</tbody>
</table>
<br>
<%= link_to 'Add new machine', new_machine_path, class:"blue-button-table" %>

<br>


  </div>
</div>

<%= render 'pages/footer' %>

app/views/machines/new.html.erb
<%= render 'pages/navbar' %>

<div class="form">
  <div class="mod-form-all">
   
<h1 class="h1-mod-form">Add a new machine</h1>

<%= render 'form', machine: @machine%>

    
  </div>
</div>

<%= render 'pages/footer' %>

app/views/machines/show.html.erb
<%= render "/pages/navbar" %>
<div class="edit-mod-form">
  <div class="edit-mod-form-all">
<section class="show_single_list">

<h1 class="h1-mod-form">Show machine</h1>
<br>
<p> 
<%= @machine.name  %>
</p>
<br>

<%= link_to "Edit", edit_machine_path(@machine) %>
<%= link_to 'Destroy', machine_path(@machine),
            method: :delete,
            data: { confirm: 'Are you sure sure?'}, class:"listing-link" %>

</div>
</div>
</section>

<%= render 'pages/footer' %>